# Debian 13 (Trixie), current stable as of 2026-01-08 (EOL 2028-08-09)
# Node 24 (Current active LTS, EOL 30 months after release at May 06, 2025)
# note: at current time, Node 25 exists, but is only active for 6 months before EOL
FROM docker.io/library/node:24-trixie

RUN mkdir -p /app
COPY package.json /app
COPY build /app/build

WORKDIR /app

# Install dependencies in the built app
RUN npm install --omit dev

CMD [ "node", "build" ]
