default:
    @just --list

# pnpm run dev  --  remember .env file with api you use, e.g: PUBLIC_API_ENDPOINT=http://localhost:3000
dev:
    #!/usr/bin/env bash
    if [ ! -f .env ]; then
        echo "error: no .env file"
        echo "To run the dev server, it must know which API to use."
        echo "Create a file .env and fill it with, f.or example:"
        echo "PUBLIC_API_ENDPOINT=http://localhost:3000"
        exit 1
    fi
    PUBLIC_ORIGIN=http://localhost:5173 pnpm run dev

# pnpm run build  --  Builds for the server, use build-local to build a local image
build:
    PUBLIC_API_ENDPOINT=http://metadict-api:3000 pnpm run build

# pnpm run build  --  
build-local:
    #!/usr/bin/env bash
    if [ ! -f .env ]; then
        echo "error: no .env file"
        echo "To build for local testing, it must know which API to use."
        echo "Create a file .env and fill it with, f.or example:"
        echo "PUBLIC_API_ENDPOINT=http://localhost:3000"
        exit 1
    fi
    pnpm run build

# podman build -t metadict-front -f Containerfile (remember to "build" first)
# Build the container image using podman (NOTE: Make sure to "build" first)
image:
    podman build -t metadict-front -f Containerfile

# Push the built image to the gtlab container registry
push-labacr:
    podman tag metadict-front gtlabcontainerregistry.azurecr.io/metadict-front
    podman push gtlabcontainerregistry.azurecr.io/metadict-front
