default:
    @just --list

# pnpm run dev
dev:
    pnpm run dev

# pnpm run build
build:
    pnpm run build

# podman build -t metadict-front -f Containerfile (remember to "build" first)
# Build the container image using podman (NOTE: Make sure to "build" first)
image:
    podman build -t metadict-front -f Containerfile

# Push the built image to the gtlab container registry
push-labacr:
    podman tag metadict-front gtlabcontainerregistry.azurecr.io/metadict-front
    podman push gtlabcontainerregistry.azurecr.io/metadict-front
