from .qvigstad_parser import QvigstadParser
from .gt_parser import GTParser
from .gt_sme_parser import GTSmeParser
from .sammallahti_parser import SammallahtiParser
from .fysihkka_parser import FysihkkaParser
from .girjjalasvuoda_parser import GirjjalasvuodaParser
from .algosatnegirji_parser import AlgosatnegirjiParser
from .ruoktumet_parser import RuoktumetParser
from .pedpsy_parser import PedPsyParser
from .nettisanakirja_parser import NettisanakirjaParser
from .apotekordliste_parser import ApotekordlisteParser
from .skoleordbok_parser import SkoleordbokParser
from .konrad_parser import KonradParser
from .medisinsk_parser import MedisinskParser
