"""
This script refreshes dictionaries that already exist in a running database,
from the .sql files generated by preprocessing/create_db_data.py.

For every "a-<slug>.sql" it looks up the dictionary with that slug, deletes
all its articles, and inserts the newly generated ones. Both happen in one
transaction, so the dictionary is never visible with no articles in it, and a
failure anywhere leaves the old contents untouched. The dictionary row itself,
and thus its id, is kept.

Use insert_dictionaries.py instead for dictionaries not yet in the database.

Typical use, after pulling the GT dictionaries and re-running
gather_dicts.py + create_db_data.py:

    python3 update_dictionaries.py -c --only 'gt*' sql_files/

If the --container (-c) argument is given, `psql` is run inside the running
podman container named "metadict-db", otherwise the hosts local `psql` is used.
"""

import argparse
import fnmatch
import shlex
import subprocess
import sys
from pathlib import Path

PODMAN_PSQL_CMD = "podman exec -i metadict-db psql -U postgres"
LOCAL_PSQL_CMD = "psql -U postgres -d postgres"

# -v ON_ERROR_STOP=1: don't keep going after a failed statement
# -q -t -A: only print what the final SELECT reports
PSQL_FLAGS = "-v ON_ERROR_STOP=1 -q -t -A -f -"

# \gset fails if the dictionary doesn't exist, which aborts the whole thing
# before anything is deleted. $DICTIONARY$ only occurs outside SQL string
# literals, and psql doesn't expand :variables inside literals, so article
# text containing colons is safe.
TEMPLATE = """\
BEGIN;

SELECT id AS dict_id FROM dictionaries WHERE slug = {slug}
\\gset

DELETE FROM articles WHERE dictionary = :dict_id;

{articles}

COMMIT;

SELECT 'id ' || :dict_id || ', ' || count(*) || ' articles'
FROM articles WHERE dictionary = :dict_id;
"""


def execute_sql(sql, run_in_container):
    base = PODMAN_PSQL_CMD if run_in_container else LOCAL_PSQL_CMD
    return subprocess.run(
        shlex.split(base) + shlex.split(PSQL_FLAGS),
        input=sql.encode("utf-8"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def update_dictionary(slug, articles_sql, run_in_container):
    sql = TEMPLATE.format(
        slug="'" + slug.replace("'", "''") + "'",
        articles=articles_sql.replace("$DICTIONARY$", ":dict_id"),
    )

    print(f"updating '{slug}'... ", end="", flush=True)
    proc = execute_sql(sql, run_in_container)
    stdout = proc.stdout.decode("utf-8").strip()
    stderr = proc.stderr.decode("utf-8").strip()

    if proc.returncode != 0 or stderr:
        # everything runs inside the transaction, so nothing was committed
        # and the old contents are still in place
        print("failed")
        sys.exit(
            f"Error: psql failed on '{slug}' (nothing was committed):\n"
            + "\n".join(stderr.split("\n")[-10:])
        )

    print(stdout or "done")


def parse_args():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "sql_scripts_folder",
        type=Path,
        metavar="sql-scripts-folder",
        help='path of the folder containing the "a-*.sql" files',
    )
    parser.add_argument(
        "-c",
        "--container",
        action="store_true",
        help="run psql inside podman image 'metadict-db'",
    )
    parser.add_argument(
        "--only",
        metavar="GLOB",
        default="*",
        help="only update dictionaries whose slug matches GLOB, e.g. 'gt*' "
        "(default: all of them)",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    path = args.sql_scripts_folder
    if not path.is_dir():
        sys.exit(f"Error: argument 'sql-scripts-folder': Not a directory ({path})")

    files = [
        (f.name[2:-4], f)
        for f in sorted(path.glob("a-*.sql"))
        if fnmatch.fnmatch(f.name[2:-4], args.only)
    ]
    if not files:
        sys.exit(f"Error: no dictionaries in {path} matched '{args.only}'")

    for slug, file in files:
        update_dictionary(slug, file.read_text(), args.container)

    print(f"all done, {len(files)} dictionaries updated")


if __name__ == "__main__":
    raise SystemExit(main())
