[package]
name = "metadict-api"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# The web framework
axum = "0.8.8"

# generic http definitions
http = "1.4.0"

# more iterators
itertools = "0.14.0"

# required in order to do source code hot reloading
listenfd = "1.0.2"

# the async runtime
tokio = { version = "1.50.0", features = ["full"] }

# postgres wrapper for use with tokio
tokio-postgres = "0.7.16"

# async connection pool of tokio-postgres connections
deadpool-postgres = { version = "0.14.1", features = ["serde"] }

# Layered config approach. Set defaults, then override/extend through
# other means. E.g. defaults in file, overriden by env vars.
config = "0.15.19"

# http specific middleware on top of tower (axum uses tower)
tower-http = { version = "0.6.8", features = ["cors", "trace"] }

# logging for async apps, core library
tracing = "0.1.44"

# a subscriber for tracing
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# SERializing and DEserializing
serde = { version = "1.0.228", features = ["derive"] }

# serializing/deserializing json
serde_json = "1.0.149"

# error wrapper
anyhow = "1.0.102"

# http client
reqwest = { version = "0.12.2", features = ["json"] }

# base64 encoding and decoding
base64 = "0.22.1"

# http cookie parsing and creation
cookie = { version = "0.18.1", features = ["percent-encode"] }

# jwt parsing and creating
jsonwebtoken = "10.3.0"

# simplifies writing custom errors
thiserror = "2.0.18"

# provide #[derive(Builder)]
derive_builder = "0.20.2"

# time and dates
chrono = "0.4.44"

# string display and fromstr from an enum
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28"
